apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  namespace: dev
  labels:
    app: java
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: javapods
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: javapods
    spec:
      containers:
        - name: myjava-container
          image:  426756113432.dkr.ecr.ap-south-1.amazonaws.com/annotation-repo:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 80       
          resources:
            requests:         
              cpu: 125m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
      restartPolicy: Always